# Generated by Django 3.1.1 on 2020-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, choices=[('PF', 'Personal Finance'), ('Sci-Fi', 'Science Fiction'), ('Tech', 'Technology'), ('Prog', 'Computer Programming'), ('PG', 'Personal Growth')], max_length=100, null=True)),
                ('author', models.ManyToManyField(to='bookstore.Author')),
            ],
        ),
    ]
