# Generated by Django 3.1.1 on 2020-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200911_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
